#!/bin/bash

for DIR in get_devices iot2simpledb
do
  echo "$DIR:"
  cd ${DIR}
  zip ${DIR}.zip index.js
  aws lambda update-function-code --function-name ${DIR} --zip-file fileb://${DIR}.zip
  rm -f ${DIR}.zip
  cd -
done
